In [1]:
import numpy as np
import numpy.linalg as la
from time import time


In [2]:
A = np.array([[4,0,-2],[2,5,4],[0,0,5]])
A

array([[ 4,  0, -2],
       [ 2,  5,  4],
       [ 0,  0,  5]])

In [3]:
eig_val, eig_vec = la.eig(A)

In [4]:
eig_val

array([5., 4., 5.])

In [5]:
eig_vec

array([[ 0.        ,  0.4472136 , -0.89442719],
       [ 1.        , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  0.4472136 ]])

In [6]:
D = np.diag(eig_val)
D

array([[5., 0., 0.],
       [0., 4., 0.],
       [0., 0., 5.]])

In [8]:
eig_vec.dot(D).dot(la.inv(eig_vec))

array([[ 4.,  0., -2.],
       [ 2.,  5.,  4.],
       [ 0.,  0.,  5.]])

In [9]:
la.matrix_power(A,5)

array([[ 1024,     0, -4202],
       [ 4202,  3125,  8404],
       [    0,     0,  3125]])

In [10]:
D_power_5 = np.diag(eig_val**5)
D_power_5

array([[3125.,    0.,    0.],
       [   0., 1024.,    0.],
       [   0.,    0., 3125.]])

In [11]:
eig_vec.dot(D_power_5).dot(la.inv(eig_vec))

array([[ 1024.,     0., -4202.],
       [ 4202.,  3125.,  8404.],
       [    0.,     0.,  3125.]])

In [15]:
A = np.random.rand(5,5)
print(A)
A = A + A.T
print(A)


[[0.15276216 0.40436623 0.08244427 0.8468194  0.26035901]
 [0.64520762 0.47976941 0.21434972 0.00397307 0.24350709]
 [0.85203999 0.21730717 0.26519084 0.78145295 0.31134523]
 [0.73742729 0.81119736 0.09772481 0.79503942 0.20133573]
 [0.30808626 0.63288956 0.19231913 0.20982146 0.98220076]]
[[0.30552432 1.04957386 0.93448426 1.58424669 0.56844528]
 [1.04957386 0.95953881 0.43165689 0.81517043 0.87639665]
 [0.93448426 0.43165689 0.53038168 0.87917776 0.50366436]
 [1.58424669 0.81517043 0.87917776 1.59007884 0.41115719]
 [0.56844528 0.87639665 0.50366436 0.41115719 1.96440151]]


In [16]:
A = A/np.expand_dims(np.sum(A,1), axis = 1)
print(A)

[[0.06877655 0.23626948 0.21036167 0.35662963 0.12796267]
 [0.25399041 0.23220248 0.10445831 0.19726622 0.21208259]
 [0.28495891 0.1316282  0.16173305 0.26809391 0.15358594]
 [0.30005633 0.15439328 0.16651627 0.30116094 0.07787317]
 [0.13146085 0.20267888 0.11647937 0.0950858  0.45429509]]


In [17]:
np.sum(A,1)

array([1., 1., 1., 1., 1.])

In [19]:
np.expand_dims(np.sum(A,1), axis = 1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [25]:
x = np.random.rand(5)
n_times = 10000000

y = x
st = time()

for i in range(n_times):
    y = A.dot(y)
print(y)
print(time() - st)
y = x
st= time()
y = la.matrix_power(A, n_times).dot(y)
print(y)
print(time() -st)

y = x


st = time()

eig_val, V = la.eig(A)
D = np.diag(eig_val)
# A^N_times y =  V eig_v^n_times V^-1 y
y = V.dot((eig_val**n_times)*la.solve(V,y))
print(y)
print(time() -st)

[0.67817729 0.67817729 0.67817729 0.67817729 0.67817729]
5.999258041381836
[0.67817729 0.67817729 0.67817729 0.67817729 0.67817729]
0.0004208087921142578
[0.67817729 0.67817729 0.67817729 0.67817729 0.67817729]
0.0008487701416015625
